### ISSUE TITLE
convert sniffles to tsv

### ISSUE THREAD

**Issue by jaesvi** [adcosta17/BreakPointAssembly#1]
Hi!
Coming for London Calling straight away. I was planning to write something to do this exact job next week, so might as well save me some time :).
I have not tried yet, but do you have a script that converts the sniffles output to the tsv format that you need in your python script?

Thanks,
Jose

**Comment by adcosta17** [comment]
Hi Jose, 

I don't have a script. The tsv is just the first 6 columns of the BEDPE format that sniffles has as an output option: https://github.com/fritzsedlazeck/Sniffles/wiki/Output#bedpe-format
I've used a subset of these calls as input just doing a grep for "TRA" as the SV type on a BEDPE file. 

Alister

**Comment by jaesvi** [comment]
Ah, great, this can work for me as well. I will try next week and let you know how it goes. Thanks!
